# pxCore FrameBuffer Library
# Simple Egl Example

CFLAGS= -I../../src -DPX_PLATFORM_X11 -Wno-write-strings -Werror
OUTDIR=../../build/x11

all: $(OUTDIR)/SimpleOpenGL

$(OUTDIR)/SimpleOpenGL: SimpleOpenGL.cpp 
	g++ -o $(OUTDIR)/SimpleOpenGL -Wall $(CFLAGS) SimpleOpenGL.cpp -L/usr/lib/x86_64/ -lX11 -L$(OUTDIR) -lpxCore -lGL -lglut -lGLEW -lrt -g



