# pxCore FrameBuffer Library
# KeyboardAndMouse Example
WAYLAND=`pkg-config wayland-client --cflags --libs`

CFLAGS= -I../../src -DPX_PLATFORM_WAYLAND -Wno-write-strings -Wall -O3 -fvisibility=hidden -g -Werror
OUTDIR=../../build/wayland

all: $(OUTDIR)/KeyboardAndMouse

$(OUTDIR)/KeyboardAndMouse: KeyboardAndMouse.cpp 
	g++ -o $(OUTDIR)/KeyboardAndMouse -Wall $(CFLAGS) KeyboardAndMouse.cpp -L$(OUTDIR) -lpxCore -lrt $(WAYLAND)



