
# pxCore FrameBuffer Library
# KeyboardAndMouse Example

CFLAGS= -I../../src -DPX_PLATFORM_X11 -Wno-write-strings -Werror
OUTDIR=../../build/x11

all: $(OUTDIR)/KeyboardAndMouse

$(OUTDIR)/KeyboardAndMouse: KeyboardAndMouse.cpp $(OUTDIR)/libpxCore.a
	g++ -o $(OUTDIR)/KeyboardAndMouse -Wall $(CFLAGS) KeyboardAndMouse.cpp -L/usr/lib/x86_64/ -lX11 -L$(OUTDIR) -lpxCore -lrt



