# pxCore FrameBuffer Library
# Sprite Example
WAYLAND=`pkg-config wayland-client --cflags --libs`

CFLAGS= -I../../src -DPX_PLATFORM_WAYLAND -Wno-write-strings -Wall -O3 -fvisibility=hidden -g -Werror
OUTDIR=../../build/wayland

all: $(OUTDIR)/Sprite

$(OUTDIR)/Sprite: Sprite.cpp 
	g++ -o $(OUTDIR)/Sprite -Wall $(CFLAGS) Sprite.cpp -L$(OUTDIR) -lpxCore -lrt $(WAYLAND)



