# pxCore FrameBuffer Library
# Sprite Example

CFLAGS= -I../../src -DPX_PLATFORM_X11 -Wno-write-strings -Werror
OUTDIR=../../build/x11

all: $(OUTDIR)/Sprite

$(OUTDIR)/Sprite: Sprite.cpp 
	g++ -o $(OUTDIR)/Sprite -Wall $(CFLAGS) Sprite.cpp -L/usr/lib/x86_64/ -lX11 -L$(OUTDIR) -lpxCore -lrt



