# pxCore FrameBuffer Library
# Sprite Example

CFLAGS= -I../../src -DPX_PLATFORM_GLUT -Wno-write-strings
OUTDIR=../../build/glut

all: $(OUTDIR)/Sprite

$(OUTDIR)/Sprite: Sprite.cpp 
	g++ -o $(OUTDIR)/Sprite -Wall $(CFLAGS) Sprite.cpp -L$(OUTDIR) -framework GLUT -framework OpenGL -lpxCore



