# pxCore FrameBuffer Library
# Mandelbrot Example


UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Darwin)
        OSCFLAGS= -framework GLUT -framework OpenGL
else
        OSCFLAGS= -lrt -lglut -lGL -lGLEW
endif

CFLAGS= -I../../src -DPX_PLATFORM_GLUT $(OSCFLAGS) -Werror
OUTDIR=../../build/glut

all: $(OUTDIR)/Mandelbrot

$(OUTDIR)/Mandelbrot: Mandelbrot.cpp
	g++ -o $(OUTDIR)/Mandelbrot -Wall Mandelbrot.cpp -lpxCore $(CFLAGS) -L$(OUTDIR)



