# pxCore FrameBuffer Library
# Simple Example

CFLAGS= -I../../src -DPX_PLATFORM_X11 -Wno-write-strings
OUTDIR=../../build/x11

all: $(OUTDIR)/Mandelbrot

$(OUTDIR)/Mandelbrot: Mandelbrot.cpp
	g++ -o $(OUTDIR)/Mandelbrot -Wall $(CFLAGS) Mandelbrot.cpp -L/usr/X11R6/lib -lX11 -L$(OUTDIR) -lpxCore



