# pxCore FrameBuffer Library
# Mandelbrot Example
WAYLAND=`pkg-config wayland-client --cflags --libs`

CFLAGS= -I../../src -DPX_PLATFORM_WAYLAND -Wno-write-strings -Wall -O3 -fvisibility=hidden -g
OUTDIR=../../build/wayland

all: $(OUTDIR)/Mandelbrot

$(OUTDIR)/Mandelbrot: Mandelbrot.cpp 
	g++ -o $(OUTDIR)/Mandelbrot -Wall $(CFLAGS) Mandelbrot.cpp -L$(OUTDIR) -lpxCore -lrt $(WAYLAND)



