# pxCore FrameBuffer Library
# Simple Example

CFLAGS= -I../../src -DPX_PLATFORM_X11 -Wno-write-strings -Werror
OUTDIR=../../build/x11

all: $(OUTDIR)/Mandelbrot

$(OUTDIR)/Mandelbrot: Mandelbrot.cpp
	g++ -o $(OUTDIR)/Mandelbrot -Wall $(CFLAGS) Mandelbrot.cpp -L/usr/lib/x86_64/ -lX11 -L$(OUTDIR) -lpxCore -lrt



