#!/bin/bash
# spark Copyright John Robinson 2005-2016

anywait(){
    for pid in "$@"; do
        while kill -0 "$pid"; do
            sleep 1.0
        done
    done
}

LOGFILE=/var/tmp/Spark_update.log

echo "Enter spark .engine_install " `date` >> $LOGFILE
echo disk image: $1 >> $LOGFILE
echo pwd: `pwd` >> $LOGFILE

if [ -e "./lastpid" ]; then

echo "Info: Waiting for spark to shut down" >> $LOGFILE
anywait `cat ./lastpid`
echo "Info: Proceeding now that spark has shut down" >> $LOGFILE

PKGNAME="$(dirname $(dirname `pwd`))"
PKGBASE="$(basename $PKGNAME)"
PKGEXT="${PKGBASE##*.}"
PKGNAMEUPDT="${PKGNAME}"

if [ $PKGEXT == "app" ]; then
    echo "Info: Running in app" >> $LOGFILE
    echo "Info: Copying software..." >> $LOGFILE
    rm -r $PKGNAME
    
    if [[ "$PKGNAME" == *pxscene.app ]] ;
    then
    echo "app name is pxscene"
      PKGNAMEUPDT=`echo "${PKGNAME/pxscene.app/Spark.app}"`
    fi
  
    cp -a $1/Spark.app $PKGNAMEUPDT
    echo $PKGNAMEUPDT >> $LOGFILE
    echo "Info: Software Updated" >> $LOGFILE
else
    echo "Warning: Not running in app bundle.  Skip." >> $LOGFILE
fi

else
echo "Warning: No file ./lastpid. Skip." >> $LOGFILE
fi


echo "Exit spark .engine_install" `date` >> $LOGFILE

