#!/bin/bash
# pxscene Copyright John Robinson 2005-2016

anywait(){
    for pid in "$@"; do
        while kill -0 "$pid"; do
            sleep 1.0
        done
    done
}

LOGFILE=/var/tmp/pxscene_update.log

echo "Enter pxscene .engine_install " `date` >> $LOGFILE
echo disk image: $1 >> $LOGFILE
echo pwd: `pwd` >> $LOGFILE

if [ -e "./lastpid" ]; then

echo "Info: Waiting for pxscene to shut down" >> $LOGFILE
anywait `cat ./lastpid`
echo "Info: Proceeding now that pxscene has shut down" >> $LOGFILE

PKGNAME="$(dirname $(dirname `pwd`))"
PKGBASE="$(basename $PKGNAME)"
PKGEXT="${PKGBASE##*.}"

if [ $PKGEXT == "app" ]; then
    echo "Info: Running in app" >> $LOGFILE
    echo "Info: Copying software..." >> $LOGFILE
    rm -r $PKGNAME
    cp -a $1/pxscene.app $PKGNAME
    echo $PKGNAME >> $LOGFILE
    echo "Info: Software Updated" >> $LOGFILE
else
    echo "Warning: Not running in app bundle.  Skip." >> $LOGFILE
fi

else
echo "Warning: No file ./lastpid. Skip." >> $LOGFILE
fi

echo "Exit pxscene .engine_install" `date` >> $LOGFILE