# pxCore FrameBuffer Library
# Multi Example

UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Darwin)
        OSCFLAGS= -framework GLUT -framework OpenGL
else
        OSCFLAGS= -lrt -lglut -lGL -lGLEW
endif

CFLAGS= -I../../src -DPX_PLATFORM_GLUT $(OSCFLAGS) -Werror
OUTDIR=../../build/glut

all: $(OUTDIR)/Multi

$(OUTDIR)/Multi: Multi.cpp 
	g++ -o $(OUTDIR)/Multi -Wall Multi.cpp -lpxCore $(CFLAGS) -L$(OUTDIR)



