# pxCore FrameBuffer Library
# Simple Example

CFLAGS= -g -I../../src -I/usr/include/directfb -DPX_PLATFORM_X11 -DENABLE_DFB -Wno-write-strings
OUTDIR=../../build/x11
LIBDIR= -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib/

all: $(OUTDIR)/Animation

$(OUTDIR)/Animation: Animation.cpp
	g++ -o $(OUTDIR)/Animation_dfb -Wall $(CFLAGS) Animation.cpp -L$(LIBDIR) -L$(OUTDIR) -lX11 -lpxCore -lrt -ldirectfb



