# pxCore FrameBuffer Library
# Simple Example

UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Darwin)
        OSCFLAGS= -framework GLUT -framework OpenGL
else
        OSCFLAGS= -lrt -lglut -lGL -lGLEW
endif

CFLAGS= -I../../src -DPX_PLATFORM_GLUT $(OSCFLAGS)	

OUTDIR=../../build/glut

all: $(OUTDIR)/Simple

$(OUTDIR)/Simple: Simple.cpp 
	g++ -o $(OUTDIR)/Simple -Wall Simple.cpp -lpxCore $(CFLAGS) -L$(OUTDIR)



