# pxCore FrameBuffer Library
# Simple Example

CFLAGS= -I../../src -DPX_PLATFORM_GLUT -Wno-write-strings
OUTDIR=../../build/glut

all: $(OUTDIR)/Simple

$(OUTDIR)/Simple: Simple.cpp 
	g++ -o $(OUTDIR)/Simple -Wall $(CFLAGS) Simple.cpp -framework GLUT -framework OpenGL -L$(OUTDIR) -lpxCore



