# pxCore FrameBuffer Library
# Simple Example
WAYLAND=`pkg-config wayland-client --cflags --libs`

CFLAGS= -I../../src -DPX_PLATFORM_WAYLAND -Wno-write-strings -Wall -O3 -fvisibility=hidden -g
OUTDIR=../../build/wayland

all: $(OUTDIR)/Simple

$(OUTDIR)/Simple: Simple.cpp 
	g++ -o $(OUTDIR)/Simple -Wall $(CFLAGS) Simple.cpp -L$(OUTDIR) -lpxCore -lrt $(WAYLAND)



