# pxCore FrameBuffer Library
# Simple Example

CFLAGS= -g -I../../src -I/usr/include/directfb -DPX_PLATFORM_X11 -DENABLE_DFB -Wno-write-strings
OUTDIR=../../build/x11
LIBDIR= -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib/

all: $(OUTDIR)/Simple

$(OUTDIR)/Simple: Simple_dfb.cpp 
	g++ -o $(OUTDIR)/Simple_dfb -Wall $(CFLAGS) Simple_dfb.cpp -L$(LIBDIR) -L$(OUTDIR) -lX11 -lpxCore -lrt -ldirectfb



