# pxCore FrameBuffer Library
# Hover Example

CFLAGS= -I../../src -DPX_PLATFORM_X11 -Wno-write-strings
OUTDIR=../../build/x11

all: $(OUTDIR)/Hover

$(OUTDIR)/Hover: Hover.cpp 
	g++ -o $(OUTDIR)/Hover -Wall $(CFLAGS) Hover.cpp -L/usr/X11R6/lib -lX11 -L$(OUTDIR) -lpxCore



