# pxCore FrameBuffer Library
# Hover Example
WAYLAND=`pkg-config wayland-client --cflags --libs`

CFLAGS= -I../../src -DPX_PLATFORM_WAYLAND -Wno-write-strings -Wall -O3 -fvisibility=hidden -g -Werror
OUTDIR=../../build/wayland

all: $(OUTDIR)/Hover

$(OUTDIR)/Hover: Hover.cpp 
	g++ -o $(OUTDIR)/Hover -Wall $(CFLAGS) Hover.cpp -L$(OUTDIR) -lpxCore -lrt $(WAYLAND)



