// JSKeyCodes.js .... JavaScript Keycodes

var JSKeyCode = {
    JS_KEY_ENTER        : 13,
    JS_KEY_BACKSPACE    : 8,
    JS_KEY_TAB          : 9,
    JS_KEY_CANCEL       : 10001,  //TODO
    JS_KEY_CLEAR        : 10002, //TODO
    JS_KEY_SHIFT        : 16,
 //   JS_KEY_SHIFT_LEFT   : 112, //10003 //TODO - special
 //   JS_KEY_SHIFT_RIGHT  : 113, //10003 //TODO - special
    JS_KEY_CONTROL      : 17,
    JS_KEY_ALT          : 18,
    JS_KEY_PAUSE        : 19,
    JS_KEY_CAPSLOCK     : 20,
    JS_KEY_ESCAPE       : 27,
    JS_KEY_SPACE        : 32,
    JS_KEY_PAGEUP       : 33,
    JS_KEY_PAGEDOWN     : 34,
    JS_KEY_END          : 35,
    JS_KEY_HOME         : 36,
    JS_KEY_LEFT         : 37,
    JS_KEY_UP           : 38,
    JS_KEY_RIGHT        : 39,
    JS_KEY_DOWN         : 40,
    JS_KEY_COMMA        : 188,
    JS_KEY_PERIOD       : 190,
    JS_KEY_SLASH        : 191,
    JS_KEY_ZERO         : 48,
    JS_KEY_ONE          : 49,
    JS_KEY_TWO          : 50,
    JS_KEY_THREE        : 51,
    JS_KEY_FOUR         : 52,
    JS_KEY_FIVE         : 53,
    JS_KEY_SIX          : 54,
    JS_KEY_SEVEN        : 55,
    JS_KEY_EIGHT        : 56,
    JS_KEY_NINE         : 57,
    JS_KEY_SEMICOLON    : 186,
    JS_KEY_EQUALS       : 187,
    JS_KEY_A            : 65,
    JS_KEY_B            : 66,
    JS_KEY_C            : 67,
    JS_KEY_D            : 68,
    JS_KEY_E            : 69,
    JS_KEY_F            : 70,
    JS_KEY_G            : 71,
    JS_KEY_H            : 72,
    JS_KEY_I            : 73,
    JS_KEY_J            : 74,
    JS_KEY_K            : 75,
    JS_KEY_L            : 76,
    JS_KEY_M            : 77,
    JS_KEY_N            : 78,
    JS_KEY_O            : 79,
    JS_KEY_P            : 80,
    JS_KEY_Q            : 81,
    JS_KEY_R            : 82,
    JS_KEY_S            : 83,
    JS_KEY_T            : 84,
    JS_KEY_U            : 85,
    JS_KEY_V            : 86,
    JS_KEY_W            : 87,
    JS_KEY_X            : 88,
    JS_KEY_Y            : 89,
    JS_KEY_Z            : 90,
    JS_KEY_OPENBRACKET  : 219,
    JS_KEY_BACKSLASH    : 220,
    JS_KEY_CLOSEBRACKET : 221,
    JS_KEY_NUMPAD0      : 96,
    JS_KEY_NUMPAD1      : 97,
    JS_KEY_NUMPAD2      : 98,
    JS_KEY_NUMPAD3      : 99,
    JS_KEY_NUMPAD4      : 100,
    JS_KEY_NUMPAD5      : 101,
    JS_KEY_NUMPAD6      : 102,
    JS_KEY_NUMPAD7      : 103,
    JS_KEY_NUMPAD8      : 104,
    JS_KEY_NUMPAD9      : 105,
    JS_KEY_MULTIPLY     : 106,
    JS_KEY_ADD          : 107,
    JS_KEY_SEPARATOR    : 27,
    JS_KEY_SUBTRACT     : 109,
    JS_KEY_DIVIDE       : 111,
    JS_KEY_F1           : 112,
    JS_KEY_F2           : 113,
    JS_KEY_F3           : 114,
    JS_KEY_F4           : 115,
    JS_KEY_F5           : 116,
    JS_KEY_F6           : 117,
    JS_KEY_F7           : 118,
    JS_KEY_F8           : 119,
    JS_KEY_F9           : 120,
    JS_KEY_F10          : 121,
    JS_KEY_F11          : 122,
    JS_KEY_F12          : 123,
    JS_KEY_DELETE       : 46,
    JS_KEY_NUMLOCK      : 144,
    JS_KEY_SCROLLLOCK   : 145,
//    JS_KEY_PRINTSCREEN  : 10036 //TODO
    JS_KEY_INSERT       : 45,
//    JS_KEY_HELP         : 10038 //TODO
    JS_KEY_DECIMAL      : 190,
    JS_KEY_BACKQUOTE    : 192,
    JS_KEY_QUOTE        : 222
};

module.exports = JSKeyCode;
